### PR TITLE
Update AISTECHSAT-2.yml

### PR DESCRIPTION
**Pull request by janvgils**
I changed the telemetry option to unknown and added the 1200 baud transmitter, currently the system seems to operating in 1k2 mode.
With this yaml file it is possible to decode the following SatNOGS observation: https://network.satnogs.org/observations/3108283/
There is no readable ASCII in the output so it is still difficult to determine with certainty that this is AISTECHSAT-2.

### CODE REVIEW

**Comment by daniestevez** [comment]
Thanks!

Some indentation was missing in the "4k8 FSK transmitter" line. You can see that one of the tests found this problem. I have added the missing indentation.

Is there a reason for changing the telemetry format to unknown? From what I know AISTECHSAT-2 is using the same format as LUME-1, plus maybe some extra message types of which we don't know the format and can't be decoded. But the LUME-1 telemetry parser was working well for the beacons transmitted when it was launched.

**Comment by daniestevez** [comment]
Well, I'm testing the SatNOGS recording you mentioned and it makes a mess with the lume1 telemetry parser. We get many
```
Could not parse telemetry beacon Error in path (parsing) -> pus_header
stream read less than specified amount, expected 7, found 6
```

With hexdump the beacons look like
```
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 160
contents = 
0000: 01 80 b7 89 01 01 02 07 0c c2 2c 5a 13 8b 8e 00 
0010: 04 57 38 50 5a 53 00 42 4f 42 43 41 54 2d 31 00 
0020: 40 b2 00 e8 00 72 00 2a 06 8e 00 fb 18 af 01 b2 
0030: 18 af 00 01 00 02 00 00 01 54 07 02 fc 04 04 00 
0040: 00 00 3a ff d1 00 04 00 4a fe e3 fe d2 00 70 00 
0050: 2a ff d6 ff cc fe e6 fe b9 fe e8 ff fa ff fa ff 
0060: fb ff fa ff fd ff fc 03 e0 00 00 03 48 e0 00 00 
0070: f2 07 5a 13 8b 8e 00 05 ff c6 ff cd ff 90 00 32 
0080: a2 8e 00 12 36 cd 22 26 1c 39 03 45 36 47 02 db 
0090: 00 00 01 00 17 8d 99 4c ac 23 b9 89 18 c8 37 88 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 73
contents = 
0000: 01 9f b7 89 57 38 50 5a 53 00 42 4f 42 43 41 54 
0010: 2d 31 00 40 a9 00 80 00 e6 02 fc 04 04 00 00 00 
0020: 3b 02 db 00 00 01 00 00 59 01 0f 04 cc 00 51 00 
0030: 50 00 5c ff 2c 00 a7 ff 20 5a 13 8b 8f 0d a2 ba 
0040: 09 49 ba 9f df 4c 0f 24 d7 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 21
contents = 
0000: 03 09 9b 49 0c cc cc 14 4b 57 40 4c 46 81 e5 ab 
0010: b5 9b 5b 2c e2 
***********************************
```

Probably I can modify the lume1 parser to do something more inteligent than just failing with these beacons, and it would be good to compare them with the beacon formats that we know of.

**Comment by janvgils** [comment]
Removing the lume parser was more a trail and error attempt and after removing it there where some decodes and Golay decode OK messages.

I wasn't aware of the fact that AISTECHSAT-2 was using the lume decoding scheme and don't know it context or values.

**Comment by daniestevez** [comment]
LUME-1 packets are CCSDS TM Space Datalink frames encapsulated in a CSP packet. However, these new packets transmitted by AISTECHSAT-2 in 436.600 MHz are not CCSDS frames. Trying to parse them as CCSDS frames shows values like
```
Container: 
    csp_header = Container: 
        priority = 1
        source = 4
        destination = 25
        destination_port = 44
        source_port = 9
        reserved = 0
        fragmentation = False
        hmac = False
        xtea = False
        rdp = True
        crc = True
    tm_header = Container: 
        version = 0
        sc_id = 92
        virtual_channel_id = 12
        virtual_channel_frame_counter = 205
        first_header_pointer = 162
        empty_frame = 0
        ocf_presence = 1
        sequence_flags = 1
        fixed_length_frame = 1
Container: 
    csp_header = Container: 
        priority = 1
        source = 4
        destination = 25
        destination_port = 45
        source_port = 9
        reserved = 0
        fragmentation = False
        hmac = False
        xtea = False
        rdp = True
        crc = True
    tm_header = Container: 
        version = 0
        sc_id = 196
        virtual_channel_id = 11
        virtual_channel_frame_counter = 99
        first_header_pointer = 851
        empty_frame = 0
        ocf_presence = 0
        sequence_flags = 1
        fixed_length_frame = 1
Container: 
    csp_header = Container: 
        priority = 1
        source = 4
        destination = 25
        destination_port = 45
        source_port = 9
        reserved = 0
        fragmentation = False
        hmac = False
        xtea = False
        rdp = True
        crc = True
    tm_header = Container: 
        version = 0
        sc_id = 68
        virtual_channel_id = 11
        virtual_channel_frame_counter = 100
        first_header_pointer = 851
        empty_frame = 0
        ocf_presence = 0
        sequence_flags = 1
        fixed_length_frame = 1
```
Note that the spacecraft ID and virtual channel information show inconsistent information.

Now my question is if AISTECHSAT-2 continues transmitting the old LUME-style packets in 436.730 MHz. If not, then it makes sense to put `unknown` in the SatYAML file. If it transmits both kinds of packets, then it makes sense to allow for both in the SatYAML file, and maybe have a way to distinguish between them.

**Comment by janvgils** [comment]
Here is a new observation with very strong signals and only 1k2 baud. https://network.satnogs.org/observations/3108395/

**Comment by janvgils** [comment]
Lets wait for a while, there is some confusion on the 1k2 and 9k6 signals and what satellites is producing what signals.

**Comment by daniestevez** [comment]
[Pierros Doppler identification](https://twitter.com/ppapadeas/status/1325361533560492039) had a small residual of just 21Hz, so this is already enough evidence to be confident that this is AISTECHSAT-2. He didn't show if there were any other near matches, although that only tends to happen shortly after launch, when several satellites are very close.

What we don't know is if AISTECHSAT-2 uses two different types of signals in two different frequencies or if it just switched frequency and type of signal (for instance because of a software or configuration update). #85 is relevant information here: apparently AISTECHSAT-3 is also transmitting new types of beacons.

**Comment by janvgils** [comment]
This is a new observation https://network.satnogs.org/observations/3109265/ the signals are ok but I am not able to decode the signals with the suggested AISTECHSAT-2 changes, my current version tries to use the telemetry: lume option but even with the cli option --hexdump there seem to be no decode possible.

```
cat /usr/local/lib/python3/dist-packages/satellites/satyaml/AISTECHSAT-2.yml 
name: AISTECHSAT-2
norad: 43768
data:
  &tlm Telemetry:
    telemetry: lume
transmitters:
  1k2 FSK downlink:
    frequency: 436.600e+6
    modulation: FSK
    baudrate: 1200
    framing: AX100 ASM+Golay
    data:
    - *tlm
  4k8 FSK downlink:
    frequency: 436.600e+6
    modulation: FSK
    baudrate: 4800
    framing: AX100 ASM+Golay
    data:
    - *tlm
  9k6 FSK downlink:
    frequency: 436.600e+6
    modulation: FSK
    baudrate: 9600
    framing: AX100 ASM+Golay
    data:
    - *tlm
```

```
gr_satellites 43768 --wavfile AISTECHSAT-2_4366_satnogs_3109265_2020-11-08T21-06-16.wav --samp_rate 48e3 --hexdump
```
```
gr::log :DEBUG: correlate_access_code_tag_bb0 - Access code: 930b51de
gr::log :DEBUG: correlate_access_code_tag_bb0 - Mask: ffffffff
gr::log :DEBUG: correlate_access_code_tag_bb1 - Access code: 930b51de
gr::log :DEBUG: correlate_access_code_tag_bb1 - Mask: ffffffff
gr::log :DEBUG: correlate_access_code_tag_bb2 - Access code: 930b51de
gr::log :DEBUG: correlate_access_code_tag_bb2 - Mask: ffffffff
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 115625
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 238833
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 245613
gr::log :DEBUG: correlate_access_code_tag_bb0 - writing tag at sample 33877
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 157925
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 185998
gr::log :DEBUG: correlate_access_code_tag_bb0 - writing tag at sample 85332
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 729490
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 769617
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 464230
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 1120433
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 572638
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 605037
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 647673
gr::log :DEBUG: correlate_access_code_tag_bb2 - writing tag at sample 1368472
gr::log :DEBUG: correlate_access_code_tag_bb1 - writing tag at sample 727590
```

To be continued

**Comment by daniestevez** [comment]
Thanks for the update. The packets in the SatNOGS observation #3109265 are not using the AX100 ASM+Golay protocol, but rather consist of a preambler of alternating 0's and 1's followed by the CCSDS syncword, as this figure shows
aistechsat2_ccsds

So this explains why the AISTECHSAT-2 decoder gives nothing. I'll try to see if I can decode these frames. It's quite possible that they are CCSDS Reed-Solomon frames.

**Comment by daniestevez** [comment]
After having a look at the frames in observation #3109265, I have found the following: there is a CCSDS syncword followed by a 125 payload which is scrambled with the CCSDS synchronous scrambler. The payload is composed of the following three pieces:
* 10 bytes of header (I'm not sure which kind of header)
* 83 bytes of data
* 32 Reed-Solomon check bytes which apply only to the data

The data plus RS check bytes form a CCSDS Reed-Solomon codeword in the conventional basis.

The following flowgraph can be used to play around with the messages:
[aistech.grc.zip](https://github.com/daniestevez/gr-satellites/files/5510601/aistech.grc.zip)

The messages look identical, except for a counter that goes through the count 0, 1, 2 (and of course that makes all the RS parity bytes change accordingnly):
```
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 125
contents = 
0000: 00 01 01 00 51 47 59 80 98 82 01 00 01 00 02 1d 
0010: 00 00 00 14 00 0a 00 93 07 00 00 01 01 00 00 00 
0020: ff ff ff ff ff ff ff ff ff 00 0a 00 00 00 00 00 
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 36 f3 f7 
0060: 27 e7 79 21 2a d9 69 3a 5a db 5e 8d 06 4f 48 60 
0070: b0 5a e4 43 ed d2 2a a4 79 be 77 ac c9 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 125
contents = 
0000: 00 01 01 00 51 47 59 80 98 82 01 00 01 01 02 1d 
0010: 00 00 00 14 00 0a 00 93 07 00 00 01 01 00 00 00 
0020: ff ff fd ff ff ff ff ff ff 00 00 00 00 00 00 00 
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 3a 0f 60 
0060: c0 e4 6e 39 6a 35 a1 10 b5 ad ae fe 80 6a c4 82 
0070: a4 3a 38 c1 54 47 18 c8 86 69 6e eb 8d 
***********************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 125
contents = 
0000: 00 01 01 00 51 47 59 80 98 82 01 00 01 02 02 1d 
0010: 00 00 00 14 00 0a 00 93 07 00 00 01 01 00 00 00 
0020: ff ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0050: 00 00 00 00 00 00 00 00 00 00 00 00 00 6c 7b c5 
0060: b1 19 18 47 63 55 6a 28 2c dd 68 83 33 c0 f0 ea 
0070: c7 9b 8c 91 b9 ae ce 86 3c 05 2f 9d d8 
```

I'm not sure what to make of this, since we have no documentation or context for this protocol, which has appeared or we have noticed suddenly. Probably the best thing for me to do would be to add a custom deframer to gr-satellites that throws away the 10 byte header and decodes the RS codeword. This will allow us to continue investigating this protocol.

**Comment by janvgils** [comment]
Thanks for all the investigations, here some information I received that maybe could help us further.

**Comment by daniestevez** [comment]
Thanks! These modes are more or less well known to me, but this is something different. Modes 2 and 5 are well supported in gr-satellites and are called "AX100 Reed-Solomon" and "AX100 ASM+Golay" respectively. I've never seen mode 4 in action (I think it carriers HDLC below the convolutional code). Mode 6 is AX.25 compliant, and mode 3 is just HDLC alone, which is pretty much AX.25 without the header.

It's not clear to me if the raw mode could be used to transmit these kind of new packets (but not to receive them, given the remarks shown in that screenshot). AISTECHSAT-2 could be using another transmitter besides the AX100.

**Comment by daniestevez** [comment]
In order to have a better tool to investigate this new packets transmitted by AISTECHSAT-2, I have rushed to implement #185 so that now we get the information about which decoder was used to decode each packet. I have also added in 9ad439f03579ee0f133641d19e05dd6dbe6902c5 a custom deframer for this new AISTECHSAT-2 protocol. The deframer throws away the 10 byte header and decodes the 83 byte Reed-Solomon--protected data.

This is working correctly with the recording:
```
$ gr_satellites AISTECHSAT-2 --wavfile satnogs_3109265_2020-11-08T21-06-16.wav --samp_rate 48e3
* MESSAGE DEBUG PRINT PDU VERBOSE *
((transmitter . 1k2 FSK custom CCSDS downlink) (rs_errors . 14))
pdu_length = 83
contents = 
0000: 01 00 01 02 02 1d 00 00 00 14 00 0a 00 93 07 00 
0010: 00 01 01 00 00 00 ff ff ff ff ff ff ff ff ff 00 
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0050: 00 00 00 
***********************************
....
```
Note the information about "1k2 FSK custom CCSDS downlink", identifying these as packets using the new protocol (the older protocol is identified as "AX100 downlink".

Now we can run the decoder with future SatNOGS recordings and check which types of messages it is transmitting.

The SatYAML file for AISTECHSAT-2 now differs from the modifications you sent in this pull request. There is a 1k2, 4k8 and 9k6 mode for each of the two protocols (AX100 and custom CCSDS-like). I haven't tried to set the frequency of each of them correctly, since currently this field is not used by gr-satellites. It would be interesting to know if AISTECHSAT-2 uses both protocols on both frequencies or not.

I'll keep this pull request open for further discussion about what AISTECHSAT-2 is doing.

**Pull request closed without merging**
