### PR TITLE
Fix baudrate for SWSU satellites

### PR DESCRIPTION
**Pull request by sv1**

### CODE REVIEW

**Comment by sv1** [comment]
Hello  Daniel,

unfortunately I can not find any official documentation but this is what I have used and successfully decoded telemetry with direwolf and gr_satellites.

**Comment by daniestevez** [comment]
Does it fail to decode with the baudrate we currently have in the repository?

**Comment by sv1** [comment]
Yes! that is why I started looking into this and made that change!

**Comment by daniestevez** [comment]
Can you share the recordings you used? It's interesting because earlier when we attempted to measure the baudrates of these satellites it turned out that the baudrates were around 1130-1135, which is well away from 1145. It could be that their baudrates are not so stable and keep changing.

**Comment by sv1** [comment]
I do not have recordings, only real-time decoding!

**Comment by daniestevez** [comment]
Then maybe it's useful to record the next time you try to receive.

**Comment by daniestevez** [comment]
Closing, since this has long been inactive and I'm not keen on changing the baudrates without some kind of precise measurement.

**Pull request closed without merging**
